ARG UBI_MINIMAL_BASE_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal
ARG UBI_BASE_IMAGE_TAG=latest
ARG CONFIG_FILE=config/config.yaml

## Rust builder ################################################################
FROM ${UBI_MINIMAL_BASE_IMAGE}:${UBI_BASE_IMAGE_TAG} AS rust-builder

ENV CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse

RUN microdnf install --disableplugin=subscription-manager -y \
        rust \
        cargo \
        gcc \
        g++ \
        cmake \
        ca-certificates \
        openssl-devel && \
    microdnf clean all

WORKDIR /app

## Orchestrator builder #########################################################
FROM rust-builder AS fms-guardrails-orchestr8-builder
ARG CONFIG_FILE=config/config.yaml

COPY .cargo/config.toml /app/.cargo/config.toml
COPY build.rs *.toml Cargo.lock LICENSE /app/
COPY ${CONFIG_FILE} /app/config/config.yaml
COPY protos/ /app/protos/
COPY src/ /app/src/
COPY tests/ /app/tests/

WORKDIR /app

ENV CFLAGS="-Wno-string-compare"

# TODO: Make releases via cargo-release
RUN cargo build --release
# Copy test resources required for executing unit tests
COPY tests/resources /app/tests/resources
RUN cargo test --lib -- --skip orchestrator::common::tasks::test::tests

## Release Image ################################################################

FROM ${UBI_MINIMAL_BASE_IMAGE}:${UBI_BASE_IMAGE_TAG} AS fms-guardrails-orchestr8-release
ARG CONFIG_FILE=config/config.yaml

COPY --from=fms-guardrails-orchestr8-builder /app/target/release/fms-guardrails-orchestr8 /app/bin/
COPY ${CONFIG_FILE} /app/config/config.yaml

RUN microdnf install -y --disableplugin=subscription-manager \
        shadow-utils \
        openssl-libs \
        openssl && \
    microdnf clean all --disableplugin=subscription-manager

RUN groupadd --system orchestr8 --gid 1001 && \
    adduser --system --uid 1001 --gid 0 --groups orchestr8 \
    --create-home --home-dir /app --shell /sbin/nologin \
    --comment "FMS Orchestrator User" orchestr8

USER orchestr8

HEALTHCHECK NONE

ENV ORCHESTRATOR_CONFIG=/app/config/config.yaml

CMD ["/app/bin/fms-guardrails-orchestr8"]

LABEL name="rhoai/odh-fms-guardrails-orchestrator-rhel9" \
      com.redhat.component="odh-fms-guardrails-orchestrator-rhel9" \
      io.k8s.display-name="odh-fms-guardrails-orchestrator-rhel9" \
      io.k8s.description="The Guardrails Orchestrator serves as a REST API orchestrator that coordinates AI text generation with safety guardrails, acting as middleware between clients and language models to provide content safety detection, filtering, and secure text generation. It manages multiple detector services, chunking services, and LLM backends through unified APIs, ensuring harmful content is blocked while enabling safe AI interactions." \
      description="The Guardrails Orchestrator serves as a REST API orchestrator that coordinates AI text generation with safety guardrails, acting as middleware between clients and language models to provide content safety detection, filtering, and secure text generation. It manages multiple detector services, chunking services, and LLM backends through unified APIs, ensuring harmful content is blocked while enabling safe AI interactions." \
      summary="A REST API orchestrator that enforces content safety by coordinating detectors, filters, and LLMs for secure AI text generation." \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
