generation:
  provider: nlp # tgis or nlp
  service:
    hostname: localhost
    port: 443
# chat_generation:
#   service:
#     hostname: localhost
#     port: 8080
chunkers:
  test_chunker:
    type: sentence
    service:
      hostname: localhost
      port: 8085
detectors:
  test_detector:
    type: text_contents
    service:
      hostname: localhost
      port: 8000
    chunker_id: test_chunker
    default_threshold: 0.5
